require 'ffi'

module TikToken
  class Encoder
    extend FFI::Library
    ffi_lib File.expand_path("../ext/tiktoken-wrapper/libttwrapper.so", File.dirname(__FILE__))

    attr_reader :token_size

    def initialize(encoding_type:)
      @encoding_type = encoding_type
      @token_size = FFI::MemoryPointer.new(:long)
      @encoder = self.class.get_encoding(encoding: encoding_type)
      raise "Failed to find encoder for #{encoding_type}" if @encoder == FFI::Pointer::NULL
    end

    def encode_string(text:)
      begin
        self.class.encode(@encoder, text, @token_size)
      rescue => e
          puts "error: #{e}"
          # free_encoder on the encoder if the encoder is allocated
          self.class.free_encoder(@encoder) if @encoder
      end
    end

    def decode_tokens(tokens:, size:)
      # takes an array of tokens gets the length of the array and calls the decode function
      # returns a string
      # Allocate memory for the array in Go
      begin
        if tokens.is_a?(FFI::Pointer)
          self.class.decode(@encoder, tokens, size)
        elsif tokens.is_a?(Array)
          tokens.size
          tpointer = self.convertTokensToPointer(tokens: tokens)
          self.class.decode(@encoder, tpointer, size)
        end
      rescue => e
          puts "error: #{e}"
          # free_encoder on the pointer if the pointer is allocated
          self.class.free_encoder(@encoder) if @encoder
      ensure
        tpointer.free if tpointer.is_a?(FFI::Pointer)
      end
    end

    def convertTokensToPointer(tokens:)
      # takes an array of tokens and converts them into a C Array
      size = tokens.size
      return FFI::MemoryPointer.new(:int, size).write_array_of_int(tokens)
    end


    def free_encoder
      self.class.freeBpe(@encoder)
      @encoder = FFI::Pointer::NULL
    end

    def example_run(text)
      tokens = encode_string(text)
      puts "size #{@token_size.read_long}"
      puts "tokens #{tokens.read_array_of_int(@token_size.read_long)}"

      value = decode_tokens(tokens: tokens, size: @token_size.read_long)
      puts "decoded tokens #{value}"

      free_encoder
    end

    def go_profile(text:, runs: 1000)
      # this performs every cgo function call
      # that is exposed to this gem where the encode
      # function is performed in a loop for the number of runs
      # a pprof file is generated by this function
      self.class.goProfile(@encoding_type, text, @token_size, runs)
    end

  private
    def self.get_encoding(encoding:)
      ptr = self.getEncoding(encoding)
      # if ptr references 0 raise an error the encoding failed
      if ptr == FFI::Pointer::NULL
        raise "Encoding failed"
      end
      ptr
    end

    attach_function :getEncoding, [:string ], :pointer
    attach_function :encode , [:pointer, :string, :pointer], :pointer
    attach_function :decode, [:pointer, :pointer, :int], :string
    attach_function :freeBpe, [:pointer], :void
    attach_function :goProfile, [:string, :string, :pointer, :int], :void
  end
end

# encoder = TikToken::Encoder.new(encoding_type: "gpt-4")
# encoder.example_run(text: "Big cats like big boxes")
