name: Publish and Release Gem
on:
  push:
    branches:
      - main
    paths:
      - "lib/tiktoken/version.rb"
  workflow_dispatch:

jobs:
  release_github_tiktoken_encoder:
    name: Publish tiktoken-encoder gem
    uses: github/sae-common-workflows/.github/workflows/publish-gem.yml@main
    with:
      gemspec_name: "tiktoken-encoder"
